# Generated by Django 4.1.7 on 2023-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=70, null=True)),
                ('empname', models.CharField(max_length=70)),
                ('empemail', models.EmailField(max_length=70)),
                ('emppassword', models.CharField(max_length=70)),
                ('empexp', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
