# Generated by Django 4.1.7 on 2023-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='empemail',
            field=models.EmailField(default='Empty@xyz.com', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='empexp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='empid',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='empname',
            field=models.CharField(default='(empty)', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='emppassword',
            field=models.CharField(default='(empty)', max_length=70),
        ),
    ]
